# This compose fragment describes development environment
# modifications to the original compose file.
version: "3"
services:
  secrets-sharing-app:
    env_file:
      - ./env/local/local.env
    image: secrets-sharing-app:local
    networks:
      - migration-net
    build:
      context: .
      dockerfile: ./env/Dockerfile
    ports:
      - "5000:5000"

networks:
  migration-net:
    external: true