version: '3.5'
services:
  secrets-api-mysql:
    env_file: ./env/local/secrets-db.local.env
    image: mysql:5.7
    # platform: linux/amd64
    volumes:
      - ./env/mysqlconf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - migration-net
    security_opt:
      - seccomp:unconfined

  secrets-migrator:
    env_file: ./env/local/secrets-db.local.env
    build:
      context: .
      dockerfile: ./env/db.Dockerfile
    networks:
      - migration-net

networks:
  migration-net:
    external: false
    name: migration-net